[misc]
assume_yes = true
disable = [
  "emacs",
  # disable nix update
  "nix",
  # disable shell update
  "shell", 
  # disable js/ts related
  "deno", "node", "pnpm", "yarn", "bun", "bun_packages",
  # disable python related
  "conda", "mamba", "pip3", "uv",
  # disable haskell
  "stack",
  "yazi",
  "bun",
]
ignore_failures = ["containers"]

[brew]
greedy_cask = true

[git]
repos = [
  # works I need to pay attention to
  "~/Developer/3rd/whisper.cpp",        # ggml-org/whisper.cpp
]

