[misc]
assume_yes = true
disable = [
  # will use doom emacs sync
  "emacs",
  # disable nix update
  "nix",
  # disable shell update
  "shell", 
  # disable js/ts related
  "deno", "node", "pnpm", "yarn", 
  # disable python related
  "mamba", "pip3", "uv",
  # disable haskell
  "stack",
]
ignore_failures = ["containers"]

[brew]
greedy_cask = true

[git]
repos = [
  # works I need to pay attention to
  "~/Developer/3rd/sglang",             # sgl-project/sglang
  "~/Developer/3rd/vllm",               # vllm-project/vllm
  "~/Developer/3rd/Mooncake",           # kvcache-ai/Mooncake
  "~/Developer/3rd/flash-fft-conv",     # HazyResearch/flash-fft-conv
  "~/Developer/3rd/btop",               # aristocratos/btop
  "~/Developer/3rd/evo2",               # ArcInstitute/evo2
  "~/Developer/3rd/vortex",             # Zymrael/vortex
  "~/Developer/3rd/savanna",            # Zymrael/savanna
  "~/Developer/3rd/MMseqs2",            # soedinglab/MMseqs2 

  # doom eamcs
  "~/.config/emacs/"
]

[commands]
"Doom Emacs" = "~/.config/emacs/bin/doom sync -u"

