[theme]
name = "dracula"

[colors]
Base       = "#F8F8F2"
Annotation = "#9580FF"
Title      = "#FF80BF"
Important  = "#FFCA80"
Guidance   = "#FF80BF"
AlertInfo  = "#8AFF80"
AlertWarn  = "#FFFF80"
AlertError = "#FF9580"
